// <auto-generated />
using BDJobsCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BDJobsCore.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BDJobsCore.Models.EmploymentStatus", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TypeName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("EmploymentStatus");
                });

            modelBuilder.Entity("BDJobsCore.Models.Job", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AgeLimit");

                    b.Property<Guid?>("CategoryID");

                    b.Property<string>("EducationDetails");

                    b.Property<Guid?>("EmploymentStatusID");

                    b.Property<string>("JobDescription")
                        .IsRequired();

                    b.Property<string>("JobResponsibility")
                        .IsRequired();

                    b.Property<string>("JobTitle")
                        .IsRequired();

                    b.Property<DateTime?>("LastDate");

                    b.Property<double>("Salary");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("Date");

                    b.Property<Guid?>("TagID");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("EmploymentStatusID");

                    b.HasIndex("TagID");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("BDJobsCore.Models.JobCategory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("JobCategory");
                });

            modelBuilder.Entity("BDJobsCore.Models.JobTag", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TagName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("JobTag");
                });

            modelBuilder.Entity("BDJobsCore.Models.Job", b =>
                {
                    b.HasOne("BDJobsCore.Models.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("BDJobsCore.Models.EmploymentStatus", "EmploymentStatus")
                        .WithMany()
                        .HasForeignKey("EmploymentStatusID");

                    b.HasOne("BDJobsCore.Models.JobTag", "JobTag")
                        .WithMany()
                        .HasForeignKey("TagID");
                });
#pragma warning restore 612, 618
        }
    }
}
